import { combineReducers } from 'redux'
import { user } from './user.redux'
import { role } from './role.redux'
import { area } from './area.redux'
import { settingServer } from './setting-server.redux'
import {remoteHost } from './setting.remoteHost.redux'
import { commHost } from './setting.commHost.redux'
import { broadcastHost } from './setting.broadcast.redux'
import { devices } from './setting.device.redux'
import { alarm } from './alarm.redux'
import { video } from './video.redux'
import { sidebar } from './sidebar.redux'
import { peo} from './peo.redux'
import { broadcast } from './broadcast.redux'
import { videSider } from './video.sider.redux'
import { status } from './status.redux'
import { watch } from './watch.redux'
import { document } from './document.redux'


export default combineReducers({user, document,role,watch, area,videSider, settingServer, remoteHost, commHost,broadcastHost,devices,alarm,video,sidebar,peo,broadcast,status})